language: php

php:
  - 7.1
  - 7.2

before_script:
  - cp .env.travis .env
  - mysql -e 'create database contacts_main;'
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate --seed

cache:
  directories:
    - vendor

notifications:
  email:
    on_failure: change
