version: '3.7'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/app
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
    depends_on:
      - app

  app:
    build: .
    depends_on:
      - mysql
      - redis
      - elasticsearch
    volumes:
      - ./:/app
    image: webapp

  horizon:
    image: webapp
    volumes:
      - ./:/app
    command: php artisan horizon

  websockets:
    image: webapp
    volumes:
      - ./:/app
    command: php artisan websockets:serve
    ports:
      - "6001:6001"

  redis:
    image: redis
    ports:
      - "6379:6379"

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=app
    volumes:
      - ./storage/tmp/db:/var/lib/mysql:cached

  elasticsearch:
    image: elasticsearch:6.7.2
    ports:
      - "9200:9200"
