version: '3.7'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - publicdata:/app/public
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile.dist
    depends_on:
      - mysql
      - redis
      - elasticsearch
    image: webapp
    volumes:
      - storagedata:/app/storage/app/
      - publicdata:/app/public/

  horizon:
    image: webapp
    command: php artisan horizon

  websockets:
    image: webapp
    command: php artisan websockets:serve
    ports:
      - "6001:6001"

  redis:
    image: redis
    ports:
      - "6379:6379"

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=app
    volumes:
      - dbdata:/var/lib/mysql:cached

  elasticsearch:
    image: elasticsearch:6.7.2
    ports:
      - "9200:9200"
    volumes:
      - searchdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node

volumes:
  storagedata:
  publicdata:
  dbdata:
  searchdata:
